{{- if .Values.apiGateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: {{ .Values.apiGateway.name }}
    {{- include "golanglab5.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
  - port: {{ .Values.apiGateway.port }}
    targetPort: {{ .Values.apiGateway.port }}
    nodePort: {{ .Values.apiGateway.service.nodePort }}
    protocol: TCP
  selector:
    app: {{ .Values.apiGateway.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apiGateway.name }}
  labels:
    app: {{ .Values.apiGateway.name }}
    {{- include "golanglab5.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiGateway.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apiGateway.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiGateway.name }}
    spec:
      containers:
      - name: api
        image: "{{ .Values.apiGateway.image }}:{{ .Values.global.imageTag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.apiGateway.port }}
          protocol: TCP
        env:
        - name: SERVICE_NAME
          value: "api"
        resources:
          {{- toYaml .Values.apiGateway.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /root/config
        livenessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.apiGateway.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: {{ .Values.apiGateway.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: {{ .Values.config.name }}
          items:
          - key: config.k8s.yaml
            path: config.yaml
{{- end }}
