global:
  scrape_interval: 5s      # 每5秒采集一次数据
  evaluation_interval: 5s   # 每5秒评估一次规则

# 数据采集配置
scrape_configs:
  # Prometheus 自身的指标
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # OpenTelemetry Collector 的指标
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  # 主机指标
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis 指标
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # MySQL 指标
  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Kafka 指标
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']