mysql:
  addr: 127.0.0.1:3306
  username: root
  password: 12345
  database: rpc
  charset: utf8mb4
redis:
  addr: 127.0.0.1:6379
  password: 12345
etcd:
  addr: 127.0.0.1:2379
kafka:
  brokers:
    - 127.0.0.1:9092
  topic: interaction-events
services:
  user:
    name: user
    addr: 127.0.0.1:11393
  video:
    name: video
    addr: 127.0.0.1:11394
  social:
    name: social
    addr: 127.0.0.1:11395
  interaction:
    name: interaction
    addr: 127.0.0.1:11396
  chat:
    name: chat
    addr: 127.0.0.1:11397